from pathlib import Path

path = Path("tests/test_robot_paper_acceptance.py")
text = path.read_text(encoding="utf-8-sig")

old = '''POLL_TIMEOUT_S = 4.0\n\n\ndef _instrument(symbol: str = SYMBOL) -> InstrumentSnapshot:\n'''
new = '''POLL_TIMEOUT_S = 4.0\n_event_sequence = 0\n\n\ndef _event_book(symbol: str, *, bid: Decimal, ask: Decimal) -> NormalizedOrderBook:\n    global _event_sequence\n    _event_sequence += 1\n    now_ms = int(time.time() * 1000)\n    return NormalizedOrderBook(\n        symbol=Symbol(symbol),\n        bids=(PriceLevel(Price(bid), Quantity(Decimal("1000"))),),\n        asks=(PriceLevel(Price(ask), Quantity(Decimal("1000"))),),\n        health=BookHealth.READY,\n        received_at_ms=now_ms,\n        available_depth=1,\n        source_generation=0,\n        source_sequence=_event_sequence,\n        source_update_id=_event_sequence,\n        source_event_at_ms=now_ms,\n        source_matching_engine_cts_ms=None,\n    )\n\n\ndef _instrument(symbol: str = SYMBOL) -> InstrumentSnapshot:\n'''
if text.count(old) != 1:
    raise SystemExit(f"constant insertion marker count={text.count(old)}")
text = text.replace(old, new, 1)

old = '''                final_candidate = _wait_until(\n                    lambda: (\n                        record\n                        if (record := candidate_record()) is not None and record.status == "OPEN"\n                        else None\n                    )\n                )\n                self.assertEqual(final_candidate.status, "OPEN")\n'''
new = '''                final_candidate = _wait_until(\n                    lambda: (\n                        record\n                        if (record := candidate_record()) is not None and record.status == "OPEN"\n                        else None\n                    )\n                )\n                self.assertEqual(final_candidate.status, "OPEN")\n\n                # Complete the real Robot PAPER lifecycle: cross TAKE through\n                # the same ordered market-event path used by production coverage.\n                take_price = protection.take_profit\n                self.assertIsNotNone(take_price)\n                tick = instrument.tick_size\n                exit_bid = take_price + tick\n                exit_ask = exit_bid + tick\n                book.set(SYMBOL, bid=exit_bid, ask=exit_ask)\n                crossing = _event_book(SYMBOL, bid=exit_bid, ask=exit_ask)\n                runtime.call(\n                    lambda owner: owner.process_robot_market_event(\n                        SYMBOL, crossing, event_id="acceptance-take",\n                        received_at_ms=crossing.received_at_ms,\n                    )\n                )\n\n                def closed_trade():\n                    current = runtime.call(\n                        lambda owner: owner.store.get_robot_trade(trade.trade_id)\n                    )\n                    return current if current is not None and current.exit_time_ms is not None else None\n\n                closed = _wait_until(closed_trade)\n                self.assertEqual(closed.exit_reason, "TAKE")\n                self.assertGreater(closed.realized_pnl_usdt, 0)\n                final_position = runtime.call(\n                    lambda owner: owner.store.get_position_projection(position_key)\n                )\n                self.assertEqual(final_position.side.value, "Flat")\n                self.assertEqual(final_position.quantity.value, Decimal("0"))\n'''
if text.count(old) != 1:
    raise SystemExit(f"acceptance insertion marker count={text.count(old)}")
text = text.replace(old, new, 1)

path.write_text(text, encoding="utf-8")
